Repository GlotPress/GlotPress, pull requests merged in 2018-10, with the labels that each got.

#933 919: Fix warnings count.
  gp-includes/things/translation-set.php
Labels: bug

#931 930: Convert nl's to br's in comments.
  gp-templates/translation-row-editor-meta.php
Labels: enhancement

#945 944: Make sure $wp is an instance of WP before use.
  gp-includes/rewrite.php
Labels: bug

#943 841: Remove PHP 7.2 deprecated functions.
  gp-includes/misc.php
  tests/phpunit/lib/testcase-request.php
  tests/phpunit/testcases/test_warnings.php
  tests/phpunit/testcases/tests_testlib/test_factory.php
Labels: bug

#932 899: Show glossary entries on the preview row.
  gp-templates/translation-row-editor.php
  gp-templates/translation-row-preview.php
  gp-templates/translation-row.php
Labels: enhancement

#934 415: URL encode the project path.
  gp-includes/url.php
Labels: bug

#926 925: Add custom filter count.
  gp-templates/translations.php
Labels: enhancement

#928 648: Fix newline and tab character filters
  assets/css/style.css
  assets/js/editor.js
  gp-includes/template.php
  gp-includes/things/translation.php
  gp-templates/translation-row-editor.php
Labels: bug, enhancement

#936 860: Add term filter scope option.
  gp-includes/things/translation.php
  gp-templates/translations.php
Labels: enhancement

#911 Android Strings: Convert escaped unicode before stripping the slashes
  gp-includes/formats/format-android.php
  tests/phpunit/data/originals.android.xml
  tests/phpunit/data/translation.android.xml
  tests/phpunit/testcases/tests_formats/test_format_android.php
Labels: bug

#964 962: Update second instance of rule name.
  phpcs.xml
Labels: bug

#965 415: Avoid URLENCODE on the double slash paths
  gp-includes/url.php
Labels: bug
