Repository GlotPress/GlotPress, pull requests merged in 2020-04, with the labels that each got.

#1028 Add PHP 7.4 to TravisCI
  .travis.yml
Labels: enhancement

#1023 fix some typing mistakes
  .github/CONTRIBUTING.md
  assets/js/vendor/jquery.tablesorter.js
  gp-includes/formats/format-android.php
  gp-includes/routes/glossary-entry.php
  gp-includes/things/project.php
Labels: bug

#1031 Replace "Polyglots Handbook" text introduced in PR1026
  gp-templates/glossary-import.php
Labels: bug

#1033 Update tablesorter library
  assets/js/vendor/jquery.tablesorter.js
  assets/js/vendor/jquery.tablesorter.min.js
  gp-includes/assets-loader.php
Labels: enhancement

#1038 Exclude build and tests file from archives
  .gitattributes
Labels: [Type] Build Tooling

#1042 Update and format composer.json to be valid
  composer.json
Labels: [Type] Build Tooling

#1044 Enable caching and parallel file processing for PHPCS
  phpcs.xml
Labels: [Type] Build Tooling

#1047 Locales: Add definitions for Papiamento
  locales/locales.php
  locales/no-variants/locales.php
Labels: [Type] Locales

#1048 Locales: Add definition for Fula
  locales/locales.php
  locales/no-variants/locales.php
Labels: [Type] Locales

#1049 Locales: Add definition for Northern Sotho
  locales/locales.php
  locales/no-variants/locales.php
Labels: [Type] Locales

#1025 Locales: Add definitions for Lower Sorbian, Ch’ti (France), Wolof
  locales/locales.php
  locales/no-variants/locales.php
Labels: [Type] Locales

#1029 Locales: Add definition for Maithili
  locales/locales.php
  locales/no-variants/locales.php
Labels: [Type] Locales

#1052 Contributing: Update recommended PHPUnit version
  .github/CONTRIBUTING.md
Labels: [Type] Build Tooling, [Type] Documentation

#1051 Thing: Fix types of integer fields by normalizing them to integers.
  gp-includes/thing.php
  gp-includes/things/original.php
  gp-includes/things/permission.php
  gp-includes/things/project.php
  gp-includes/things/translation-set.php
  gp-includes/things/translation.php
  gp-includes/things/validator-permission.php
  tests/phpunit/testcases/tests_things/test_thing_glossary.php
Labels: [Type] Bug

#1057 Fix WPCS: WordPress.WP.I18n.MissingTranslatorsComment
  gp-includes/format.php
  gp-includes/formats/format-properties.php
  gp-includes/routes/glossary-entry.php
  gp-includes/routes/project.php
  gp-includes/routes/translation.php
  gp-includes/things/project.php
  gp-includes/validation.php
  gp-includes/warnings.php
  gp-templates/footer.php
  gp-templates/glossary-view.php
  gp-templates/helper-functions.php
  gp-templates/locale.php
  gp-templates/profile-public.php
  gp-templates/project-import.php
  gp-templates/project-mass-create-sets.php
  gp-templates/project-permissions.php
  gp-templates/project.php
  gp-templates/redirect.php
  gp-templates/translation-set-delete.php
  gp-templates/translation-set-edit.php
  gp-templates/translations.php
Labels: [Type] Enhancement

#1059 Fix WPCS: WordPress.WhiteSpace.ControlStructureSpacing
  gp-includes/cli/add-admin.php
  gp-includes/cli/branch-project.php
  gp-includes/cli/remove-multiple-currents.php
  gp-includes/cli/translation-set.php
  gp-includes/cli/upgrade-set-permissions.php
  gp-includes/format.php
  gp-includes/formats/format-android.php
  gp-includes/formats/format-pomo.php
  gp-includes/formats/format-properties.php
  gp-includes/formats/format-resx.php
  gp-includes/formats/format-strings.php
  gp-includes/install-upgrade.php
  gp-includes/misc.php
  gp-includes/route.php
  gp-includes/router.php
  gp-includes/routes/glossary-entry.php
  gp-includes/routes/project.php
  gp-includes/routes/translation.php
  gp-includes/system.php
  gp-includes/template.php
  gp-includes/thing.php
  gp-includes/things/glossary.php
  gp-includes/things/original.php
  gp-includes/things/project.php
  gp-includes/things/translation.php
  gp-includes/validation.php
  gp-templates/glossary-entry-row.php
  gp-templates/glossary-view.php
  gp-templates/header.php
  gp-templates/helper-functions.php
  gp-templates/locale.php
  gp-templates/profile-public.php
  gp-templates/project-permissions.php
  gp-templates/project.php
  gp-templates/projects.php
  gp-templates/translations.php
Labels: [Type] Enhancement

#1061 Fix WPCS: WordPress.WP.I18n.MissingTranslatorsComment
  gp-templates/translations.php
Labels: [Type] Enhancement

#1062 Fix WPCS: WordPress.WhiteSpace.OperatorSpacing
  gp-includes/advanced-permissions.php
  gp-includes/cli/import-originals.php
  gp-includes/misc.php
  gp-includes/route.php
  gp-includes/routes/project.php
  gp-includes/routes/translation-set.php
  gp-includes/routes/translation.php
  gp-includes/template-links.php
  gp-includes/template.php
  gp-includes/thing.php
  gp-includes/things/original.php
  gp-includes/things/project.php
  gp-includes/things/translation.php
  gp-includes/things/validator-permission.php
  gp-includes/url.php
  gp-includes/validation.php
  gp-templates/locale.php
  gp-templates/project-import.php
  gp-templates/project-permissions.php
  gp-templates/project.php
  gp-templates/translation-set-edit.php
  gp-templates/translation-set-form.php
  gp-templates/translation-set-new.php
  gp-templates/translations.php
Labels: [Type] Enhancement

#1063 Fix WPCS: WordPress.PHP.YodaConditions.NotYoda
  gp-includes/advanced-permissions.php
  gp-includes/cli/import-originals.php
  gp-includes/formats/format-properties.php
  gp-includes/formats/format-strings.php
  gp-includes/misc.php
  gp-includes/rewrite.php
  gp-includes/route.php
  gp-includes/routes/locale.php
  gp-includes/routes/translation.php
  gp-includes/strings.php
  gp-includes/template.php
  gp-includes/thing.php
  gp-includes/things/original.php
  gp-includes/things/translation.php
  gp-includes/validation.php
  gp-templates/locale.php
  gp-templates/project-import.php
Labels: [Type] Enhancement

#1064 Add missing newline at end of files
  gp-templates/404.php
  gp-templates/project.api.php
  gp-templates/projects.api.php
Labels: [Type] Enhancement

#1066 Fix WPCS: WordPress.Arrays...
  glotpress.php
  gp-includes/cli/add-admin.php
  gp-includes/cli/remove-multiple-currents.php
  gp-includes/cli/upgrade-set-permissions.php
  gp-includes/formats/format-ngx.php
  gp-includes/meta.php
  gp-includes/misc.php
  gp-includes/rewrite.php
  gp-includes/route.php
  gp-includes/router.php
  gp-includes/routes/glossary-entry.php
  gp-includes/routes/glossary.php
  gp-includes/routes/locale.php
  gp-includes/routes/profile.php
  gp-includes/routes/project.php
  gp-includes/routes/translation.php
  gp-includes/strings.php
  gp-includes/template-links.php
  gp-includes/template.php
  gp-includes/thing.php
  gp-includes/things/glossary-entry.php
  gp-includes/things/original.php
  gp-includes/things/permission.php
  gp-includes/things/project.php
  gp-includes/things/translation-set.php
  gp-includes/things/translation.php
  gp-includes/things/validator-permission.php
  gp-includes/validation.php
  gp-includes/warnings.php
  gp-templates/404.api.php
  gp-templates/glossary-edit.php
  gp-templates/glossary-import.php
  gp-templates/glossary-new.php
  gp-templates/glossary-view.php
  gp-templates/locale.php
  gp-templates/profile-public.api.php
  gp-templates/project-import.php
  gp-templates/project-mass-create-sets.php
  gp-templates/project.api.php
  gp-templates/settings-edit.php
  gp-templates/translations.php
Labels: [Type] Enhancement

#1069 Fix syntax error by removing a stray M character
  gp-includes/things/translation.php
Labels: [Type] Bug

#1073 Use strict type check for in_array() and array_search().
  gp-includes/cli/translation-set.php
  gp-includes/misc.php
  gp-includes/routes/locale.php
  gp-includes/routes/profile.php
  gp-includes/template.php
  gp-includes/thing.php
  gp-includes/things/translation.php
Labels: [Type] Bug

#1075 Fix WPCS: Generic.Formatting
  gp-includes/formats/format-resx.php
  gp-includes/routes/project.php
  gp-includes/template.php
  gp-includes/thing.php
  gp-includes/things/project.php
  gp-includes/things/translation.php
  gp-includes/things/validator-permission.php
  gp-templates/helper-functions.php
  gp-templates/locale.php
Labels: [Type] Enhancement

#1074 Use proper encoding/decoding in GP_Project::by_path()
  gp-includes/things/project.php
  gp-includes/url.php
  gp-templates/project-form.php
  tests/phpunit/testcases/tests_things/test_thing_project.php
Labels: [Type] Bug

#1076 Fix WPCS: Generic.(...)
  glotpress.php
  gp-includes/advanced-permissions.php
  gp-includes/cli/remove-multiple-currents.php
  gp-includes/cli/translation-set.php
  gp-includes/cli/upgrade-set-permissions.php
  gp-includes/format.php
  gp-includes/formats/format-android.php
  gp-includes/formats/format-jed1x.php
  gp-includes/formats/format-ngx.php
  gp-includes/formats/format-pomo.php
  gp-includes/formats/format-properties.php
  gp-includes/formats/format-resx.php
  gp-includes/formats/format-strings.php
  gp-includes/meta.php
  gp-includes/misc.php
  gp-includes/rewrite.php
  gp-includes/route.php
  gp-includes/router.php
  gp-includes/routes/glossary-entry.php
  gp-includes/routes/glossary.php
  gp-includes/routes/locale.php
  gp-includes/routes/profile.php
  gp-includes/routes/project.php
  gp-includes/routes/translation-set.php
  gp-includes/routes/translation.php
  gp-includes/schema.php
  gp-includes/strings.php
  gp-includes/template.php
  gp-includes/thing.php
  gp-includes/things/administrator-permission.php
  gp-includes/things/glossary-entry.php
  gp-includes/things/glossary.php
  gp-includes/things/original.php
  gp-includes/things/permission.php
  gp-includes/things/project.php
  gp-includes/things/translation-set.php
  gp-includes/things/translation.php
  gp-includes/things/validator-permission.php
  gp-includes/url.php
  gp-includes/validation.php
  gp-includes/warnings.php
  gp-settings.php
  gp-templates/glossary-delete.php
  gp-templates/helper-functions.php
  gp-templates/locale.php
  gp-templates/project-import.php
  gp-templates/project.php
  gp-templates/translations.php
Labels: [Type] Enhancement

#1077 Travis: Reorder jobs by using recent PHP versions first
  .travis.yml
Labels: [Type] Build Tooling

#1078 Ignore composer.lock in git archives
  .gitattributes
Labels: [Type] Build Tooling

#1080 Locales: Define German (Austria) as a variant of German
  locales/locales.php
Labels: [Type] Locales

#1082 Translations: Add a 'with plural' filter for translations
  gp-includes/things/translation.php
  gp-templates/translations.php
  phpcs.xml.dist
Labels: [Type] Enhancement

#1083 Remove unused 'row' attribute for translation edit link
  gp-templates/translation-row-preview.php
  phpcs.xml.dist
Labels: [Type] Bug

#1081 Fix import of translations in JSON format
  gp-includes/formats/format-jed1x.php
  gp-includes/formats/format-json.php
  tests/phpunit/testcases/tests_formats/test_format_jed1x.php
  tests/phpunit/testcases/tests_formats/test_format_json.php
Labels: [Type] Bug

#1090 Improve position and markup of filter toolbar
  .jshintrc
  assets/css/style.css
  assets/css/style.min.css
  assets/js/editor.min.js
  assets/js/translations-page.js
  assets/js/translations-page.min.js
  gp-templates/translations.php
Labels: [Type] Enhancement

#1091 Update powered by URL to https://glotpress.blog/
  gp-templates/footer.php
Labels: [Type] Enhancement

#1092 PHPCS: i18n functions are considered safe for translations
  phpcs.xml.dist
Labels: [Type] Build Tooling

#1093 Restore line-height for bulk actions.
  assets/css/style.css
  assets/css/style.min.css
  gp-includes/assets-loader.php
Labels: [Type] Bug

#1094 Rewrite: Remove unused $wp import
  gp-includes/rewrite.php
Labels: [Type] Bug

#1095 Add filters for display of titles and descriptions
  assets/css/style.css
  assets/css/style.min.css
  gp-includes/assets-loader.php
  gp-includes/default-filters.php
  gp-templates/glossary-view.php
  gp-templates/header.php
  gp-templates/project.php
  gp-templates/translation-row-editor-meta.php
Labels: [Type] Enhancement

#1096 Glossary: Use the human-readable name of speech part in tables
  gp-templates/glossary-entry-row.php
Labels: [Type] Bug

#1098 Add and improve various output escaping
  glotpress.php
  gp-includes/route.php
  gp-includes/routes/translation.php
  gp-includes/template-links.php
  gp-includes/template.php
  gp-includes/validation.php
  gp-templates/glossary-edit.php
  gp-templates/glossary-entry-row.php
  gp-templates/glossary-new.php
  gp-templates/glossary-view.php
  gp-templates/helper-functions.php
  gp-templates/locale.php
  gp-templates/locales.php
  gp-templates/profile-public.php
  gp-templates/project-branch.php
  gp-templates/project-edit.php
  gp-templates/project-import.php
  gp-templates/project-permissions.php
  gp-templates/project.php
  gp-templates/redirect.php
  gp-templates/settings-edit.php
  gp-templates/translation-row-editor-meta-status.php
  gp-templates/translation-row-editor-meta.php
  gp-templates/translation-row-editor.php
  gp-templates/translation-row-preview.php
  gp-templates/translation-set-edit.php
  gp-templates/translation-set-new.php
  gp-templates/translations.php
  phpcs.xml.dist
Labels: [Type] Enhancement

#1012 Locales: Fix plural expression for Persian locales
  locales/locales.php
  locales/no-variants/locales.php
Labels: [Type] Locales
