Repository GlotPress/GlotPress, pull requests merged in 2022-03, with the labels that each got.

#1323 Tests: Replace hardcoded dates which dynamic dates based on current date
  tests/phpunit/testcases/test_translations.php
Labels: [Type] Code Quality

#1313 Glossary: Fix wrong uasort usage
  gp-templates/helper-functions.php
Labels: [Type] Bug

#1292 `prepare_original()` for strings with plurals in editor
  gp-templates/translation-row-editor.php
Labels: [Type] Bug

#1309 Locales: Update native name for Chinese (Hong Kong)
  locales/locales.php
Labels: [Type] Locales

#1342 Add the Entry as context to the gp_import_original_array filter.
  gp-includes/things/original.php
Labels: [Type] Enhancement

#1344 Translations: Add a 'Waiting approval, including fuzzy' status filter option
  gp-templates/translations.php
Labels: [Type] Enhancement

#1345 Translations: Add a 'Fuzzy' status filter option
  gp-templates/translations.php
Labels: [Type] Enhancement

#1346 Translations: Improve spacing in filters box
  assets/css/style.css
  assets/css/style.min.css
  gp-templates/translations.php
Labels: [Type] Enhancement

#1347 Fix `$gp.showhide` so it does hide other open containers again
  assets/css/style.css
  assets/css/style.min.css
  assets/js/common.js
  assets/js/common.min.js
Labels: [Type] Bug

#1341 Allow specifying the priority for PO import/exports in the `flags`.
  gp-includes/things/original.php
  gp-includes/things/translation.php
  tests/phpunit/testcases/tests_things/test_thing_original.php
Labels: [Type] Enhancement

#1348 Add workflows to automate deployment to WordPress.org plugin directory
  .gitattributes
  .github/workflows/deploy-wporg-assets.yml
  .github/workflows/deploy-wporg-plugin.yml
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  readme.txt
Labels: [Type] Build Tooling

#1359 1169: Fix Glossary Tooltip to match terms with multiple words and words with hyphens
  gp-templates/helper-functions.php
  tests/phpunit/testcases/test_template_helper_functions.php
Labels: [Type] Bug

#1360 Translations: Convert status filter into list of checkboxes
  assets/js/translations-page.js
  assets/js/translations-page.min.js
  gp-includes/assets-loader.php
  gp-templates/translations.php
Labels: [Type] Enhancement

#1364 Glossary: Add new validation methods to validate terms
  gp-includes/misc.php
  gp-includes/routes/glossary-entry.php
  gp-includes/things/glossary-entry.php
  gp-includes/validation.php
  tests/phpunit/testcases/test_validation.php
Labels: [Type] Bug
