Repository GlotPress/GlotPress, pull requests merged in 2022-09, with the labels that each got.

#1479 Add the alphabet for each locale
  locales/locales.php
Labels: [Type] Enhancement

#1459 Add a npm command to automatically fix the potentially fixable errors
  package.json
Labels: [Type] Build Tooling

#1482 Add word count type to each Locale
  locales/locales.php
Labels: [Type] Locales

#1464 Fixes deprecation notice in PHP8 for usort returning bool
  gp-includes/routes/locale.php
  gp-includes/routes/project.php
Labels: [Type] Code Quality

#1428 1423: Add "Last Modified" column to Glossary
  assets/css/style.css
  gp-templates/glossary-entry-row.php
  gp-templates/glossary-view.php
Labels: [Type] Enhancement
