Repository GlotPress/GlotPress, pull requests merged in 2022-04, with the labels that each got.

#1378 Glossary: Provide fallback if term splitting has failed
  gp-templates/helper-functions.php
Labels: [Type] Bug

#1393 Glossary: Add missing primary styles to import button
  gp-templates/glossary-import.php
Labels: [Type] Bug

#1396 Simplify global footer layout to support custom content
  assets/css/style.css
  assets/css/style.min.css
  gp-includes/assets-loader.php
Labels: [Type] Bug

#1406 Fix readme duplicate strings and update links
  README.md
  readme.txt
Labels: [Type] Documentation

#1407 1405: Update readme texts
  readme.txt
Labels: [Type] Documentation

#1417 Update minimum required PHP version to 7.4
  .github/workflows/phpunit.yml
  glotpress.php
  readme.txt
Labels: [Type] Performance, [Type] Code Quality

#1408 Speed improvement for gp_levenshtein().
  gp-includes/strings.php
Labels: [Type] Performance
